In [253]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plot

In [254]:
df = pd.read_csv("loan_approval_data.csv")
df

,Applicant_ID,Applicant_Income,Coapplicant_Income,Employment_Status,Age,Marital_Status,Dependents,Credit_Score,Existing_Loans,DTI_Ratio,Savings,Collateral_Value,Loan_Amount,Loan_Term,Loan_Purpose,Property_Area,Education_Level,Gender,Employer_Category,Loan_Approved
0,1.0,17795.0,1387.0,Salaried,51.0,Married,0.0,637.0,4.0,0.53,19403.0,45638.0,16619.0,84.0,Personal,Urban,Not Graduate,Female,Private,No
1,2.0,2860.0,2679.0,Salaried,46.0,Married,3.0,621.0,2.0,0.30,2580.0,49272.0,38687.0,NaN,Car,Semiurban,Graduate,NaN,Private,No
2,3.0,7390.0,2106.0,Salaried,25.0,Single,2.0,674.0,4.0,0.20,13844.0,6908.0,27943.0,72.0,NaN,Urban,NaN,Female,Government,Yes
3,4.0,13964.0,8173.0,Salaried,40.0,Married,2.0,579.0,3.0,0.31,9553.0,10844.0,27819.0,60.0,Business,Rural,Graduate,Female,Government,No
4,5.0,13284.0,4223.0,Self-employed,31.0,Single,2.0,721.0,1.0,0.29,9386.0,37629.0,12741.0,72.0,Car,NaN,Graduate,Male,Private,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996.0,NaN,9092.0,Salaried,58.0,Married,0.0,557.0,0.0,0.59,5370.0,43563.0,8311.0,72.0,Personal,NaN,Not Graduate,Male,Unemployed,No
996,997.0,3279.0,6356.0,Self-employed,58.0,Married,1.0,646.0,3.0,0.19,NaN,18361.0,22563.0,12.0,Business,Urban,Graduate,Female,Government,No
997,998.0,15192.0,8433.0,Contract,48.0,Single,1.0,666.0,1.0,0.40,8581.0,41335.0,16203.0,24.0,Home,Rural,Graduate,Male,MNC,No
998,999.0,9083.0,7380.0,Unemployed,50.0,Single,1.0,748.0,3.0,0.31,13491.0,8933.0,10290.0,36.0,Personal,Urban,Graduate,Male,Private,Yes
999,1000.0,13093.0,2385.0,Salaried,23.0,Married,1.0,613.0,3.0,0.32,12436.0,25816.0,35818.0,48.0,Personal,Semiurban,Graduate,NaN,Private,No

In [255]:
df = df.dropna(subset='Loan_Approved')

In [256]:
df = df.drop(['Applicant_ID','Gender'], axis=1)
df['Total_Income'] = df['Applicant_Income'] + df['Coapplicant_Income']
df

,Applicant_Income,Coapplicant_Income,Employment_Status,Age,Marital_Status,Dependents,Credit_Score,Existing_Loans,DTI_Ratio,Savings,Collateral_Value,Loan_Amount,Loan_Term,Loan_Purpose,Property_Area,Education_Level,Employer_Category,Loan_Approved,Total_Income
0,17795.0,1387.0,Salaried,51.0,Married,0.0,637.0,4.0,0.53,19403.0,45638.0,16619.0,84.0,Personal,Urban,Not Graduate,Private,No,19182.0
1,2860.0,2679.0,Salaried,46.0,Married,3.0,621.0,2.0,0.30,2580.0,49272.0,38687.0,NaN,Car,Semiurban,Graduate,Private,No,5539.0
2,7390.0,2106.0,Salaried,25.0,Single,2.0,674.0,4.0,0.20,13844.0,6908.0,27943.0,72.0,NaN,Urban,NaN,Government,Yes,9496.0
3,13964.0,8173.0,Salaried,40.0,Married,2.0,579.0,3.0,0.31,9553.0,10844.0,27819.0,60.0,Business,Rural,Graduate,Government,No,22137.0
4,13284.0,4223.0,Self-employed,31.0,Single,2.0,721.0,1.0,0.29,9386.0,37629.0,12741.0,72.0,Car,NaN,Graduate,Private,Yes,17507.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,NaN,9092.0,Salaried,58.0,Married,0.0,557.0,0.0,0.59,5370.0,43563.0,8311.0,72.0,Personal,NaN,Not Graduate,Unemployed,No,NaN
996,3279.0,6356.0,Self-employed,58.0,Married,1.0,646.0,3.0,0.19,NaN,18361.0,22563.0,12.0,Business,Urban,Graduate,Government,No,9635.0
997,15192.0,8433.0,Contract,48.0,Single,1.0,666.0,1.0,0.40,8581.0,41335.0,16203.0,24.0,Home,Rural,Graduate,MNC,No,23625.0
998,9083.0,7380.0,Unemployed,50.0,Single,1.0,748.0,3.0,0.31,13491.0,8933.0,10290.0,36.0,Personal,Urban,Graduate,Private,Yes,16463.0
999,13093.0,2385.0,Salaried,23.0,Married,1.0,613.0,3.0,0.32,12436.0,25816.0,35818.0,48.0,Personal,Semiurban,Graduate,Private,No,15478.0

In [257]:
X = df.drop(['Loan_Approved','Applicant_Income','Coapplicant_Income'],axis=1)
y = df['Loan_Approved']

In [258]:
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

X_num = X.select_dtypes(include='number').columns
X_obj = X.select_dtypes(include='object').columns

impute_num = SimpleImputer(strategy='mean')
impute_obj = SimpleImputer(strategy='most_frequent')

X_train[X_num] = impute_num.fit_transform(X_train[X_num])
X_test[X_num] = impute_num.transform(X_test[X_num])

X_train[X_obj] = impute_obj.fit_transform(X_train[X_obj])
X_test[X_obj] = impute_obj.transform(X_test[X_obj])

In [259]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train[X_num] = pd.DataFrame(
    scaler.fit_transform(X_train[X_num]),
    columns=X_num,
    index=X_train.index
)

X_test[X_num] = pd.DataFrame(
    scaler.transform(X_test[X_num]),
    columns=X_num,
    index=X_test.index
)

In [260]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

risk_cols = ['Loan_Purpose', 'Education_Level']
    
r0_map = {
    'Home' : 1,
    'Car' : 2,
    'Business' : 3,
    'Education' : 4,
    'Personal' : 5,
    'Graduate' : 1,
    'Not Graduate' : 2
}

for risk_col in risk_cols:
    X_train[risk_col] = X_train[risk_col].map(r0_map)
    X_test[risk_col] = X_test[risk_col].map(r0_map)


ohe_cols = ['Employment_Status', 'Marital_Status', 'Property_Area', 'Employer_Category']
ohe = OneHotEncoder(drop='first', sparse_output=False, handle_unknown='ignore')

X_train_encoded = pd.DataFrame(
    ohe.fit_transform(X_train[ohe_cols]),
    columns=ohe.get_feature_names_out(ohe_cols),
    index=X_train.index
)

X_test_encoded = pd.DataFrame(
    ohe.transform(X_test[ohe_cols]),
    columns=ohe.get_feature_names_out(ohe_cols),
    index=X_test.index
)

# Concatenate back with the rest of the features
X_train = pd.concat([X_train.drop(columns=ohe_cols), X_train_encoded], axis=1)
X_test  = pd.concat([X_test.drop(columns=ohe_cols), X_test_encoded], axis=1)


le = LabelEncoder()
y_train = le.fit_transform(y_train)
y_test = le.transform(y_test)

In [264]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression()
lr.fit(X_train,y_train)
y_pred_lr = lr.predict(X_test)

from sklearn.metrics import precision_score, recall_score, f1_score

print("Logistic Regression")
print("Precision Score = ",precision_score(y_test, y_pred_lr))
print("Recall Score = ",recall_score(y_test, y_pred_lr))
print("F1 Score = ",f1_score(y_test, y_pred_lr))

Logistic Regression
Precision Score =  0.8888888888888888
Recall Score =  0.7868852459016393
F1 Score =  0.8347826086956521

In [265]:
from sklearn.naive_bayes import GaussianNB

nb = GaussianNB()
nb.fit(X_train, y_train)
y_pred_nb = nb.predict(X_test)

from sklearn.metrics import precision_score, recall_score, f1_score

print("Naive Bayes")
print("Precision Score = ",precision_score(y_test, y_pred_nb))
print("Recall Score = ",recall_score(y_test, y_pred_nb))
print("F1 Score = ",f1_score(y_test, y_pred_nb))

Naive Bayes
Precision Score =  0.8846153846153846
Recall Score =  0.7540983606557377
F1 Score =  0.8141592920353983

In [273]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors = 15)
knn.fit(X_train, y_train)
y_pred_knn = knn.predict(X_test)

from sklearn.metrics import precision_score, recall_score, f1_score

print("KNN Classifier")
print("Precision Score = ",precision_score(y_test, y_pred_knn))
print("Recall Score = ",recall_score(y_test, y_pred_knn))
print("F1 Score = ",f1_score(y_test, y_pred_knn))

KNN Classifier
Precision Score =  0.8518518518518519
Recall Score =  0.7540983606557377
F1 Score =  0.8